// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations/DDL must use the DIRECT (session pooler, 5432) connection —
    // the pgBouncer transaction pooler (DATABASE_URL, 6543) can't run them.
    // The app runtime uses DATABASE_URL via the driver adapter (lib/server/db.ts).
    url: process.env["DIRECT_URL"],
  },
});
